In [19]:
import numpy as np
from tensorflow import keras

In [55]:
x = np.linspace(-4,4,9)
y = np.linspace(-9,7,9)
print(x,x.shape)
print(y,y.shape)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.] (9,)
[-9. -7. -5. -3. -1.  1.  3.  5.  7.] (9,)


In [56]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

In [57]:
model.fit(x,y,epochs=600)

Epoch 1/600
1/1 [==============================] - 0s 122ms/step - loss: 5.2209
Epoch 2/600
1/1 [==============================] - 0s 1ms/step - loss: 4.1308
Epoch 3/600
1/1 [==============================] - 0s 1ms/step - loss: 3.3037
Epoch 4/600
1/1 [==============================] - 0s 1ms/step - loss: 2.6745
Epoch 5/600
1/1 [==============================] - 0s 2ms/step - loss: 2.1942
Epoch 6/600
1/1 [==============================] - 0s 2ms/step - loss: 1.8262
Epoch 7/600
1/1 [==============================] - 0s 2ms/step - loss: 1.5427
Epoch 8/600
1/1 [==============================] - 0s 1ms/step - loss: 1.3229
Epoch 9/600
1/1 [==============================] - 0s 1ms/step - loss: 1.1514
Epoch 10/600
1/1 [==============================] - 0s 1ms/step - loss: 1.0163
Epoch 11/600
1/1 [==============================] - 0s 2ms/step - loss: 0.9088
Epoch 12/600
1/1 [==============================] - 0s 2ms/step - loss: 0.8224
Epoch 13/600
1/1 [==============================] - 0s 3ms/

In [58]:
print(model.predict([6, 7, 8]))

[[11.000004]
 [13.000003]
 [15.000003]]


In [46]:
del model